owner: ershaaa
repo: status-page       

sites:
  - name: API Health
    url: https://api.adanothe.com/healthz
    expectedStatus: 200        
    check: "http"             
    interval: 5                

status-website:
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "API Status"
  introTitle: "API Status Page"
  introMessage: "Monitoring status of https://api.adanothe.com/healthz. Powered by Upptime and GitHub Actions."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ershaaa/status-page

